version = 0.1
[dev.deploy.parameters]
stack_name = "reserve-rec-api"
resolve_s3 = true
s3_prefix = "reserve-rec-api"
region = "ca-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"reserve-rec\" Stage=\"api\""
image_repositories = []
